slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: "mapping"
    odom_frame: "odom"
    base_frame: "base_footprint"
    map_frame: "map"
    publish_period_sec: 0.05
    transform_tolerance: 0.1
    map_update_interval: 5.0
    max_laser_range: 10.0
    laser_min_range: 0.2
    min_score: 0.4
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    scan_topic: "/scan" # ตั้งค่าช่องทางที่ LIDAR ส่งข้อมูล
    max_angular_speed: 0.3
    max_linear_speed: 0.2

